In [1]:
import numpy as np                                                      # type: ignore
from sklearn.datasets import load_iris                                  # type: ignore
from sklearn.metrics import accuracy_score , confusion_matrix           # type: ignore
from sklearn.model_selection import StratifiedKFold                     # type: ignore
from sklearn.linear_model import LogisticRegression                     # type: ignore

X, y = load_iris(return_X_y=True)

In [ ]:
skf = StratifiedKFold(n_splits = 10)
predict = np.zeros(y.shape[0])

In [3]:
for train,test in skf.split(X,y):
    x_train = X[train]
    x_test = X[test]
    y_train = y[train]
    y_test = y[test]
    logreg = LogisticRegression()
    logreg.fit(x_train , y_train)
    result = logreg.predict(x_test)
    predict[test] = result
    
    print(f'train data :\n{train}')
    print(f'test data :\n{test}')
    print(f'result = {result}')
    print(f'this accuracy = {accuracy_score(y_test , result):.2f}')
    print('===============================\n')

train data :
[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122
 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140
 141 142 143 144 145 146 147 148 149]
test data :
[  0   1   2   3   4  50  51  52  53  54 100 101 102 103 104]
result = [0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
this accuracy = 1.00

train data :
[  0   1   2   3   4  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80 

c:\Users\abdal\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
print(f'total accuracy   : {accuracy_score(y , predict):.2f}')

conf = confusion_matrix(y , predict)
print(f'confusion matrix :\n{conf}')

total accuracy   : 0.97
confusion matrix :
[[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]
