In [6]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
#----------------------------------------------------

## Polynomial the Data:
"""
scaler = PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)   
X = scaler.fit_transform(X)

interaction_only : مش هيعرض الاسس هيعرض المضروب بس  
"""

'\nscaler = PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)   \nX = scaler.fit_transform(X)\n\ninteraction_only : مش هيعرض الاسس هيعرض المضروب بس  \n'

In [7]:
X = np.arange(6).reshape(3, 2)
print(X)

[[0 1]
 [2 3]
 [4 5]]


In [8]:
poly = PolynomialFeatures(degree=2 , include_bias = True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [9]:
poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])