In [1]:
import numpy as np
from sklearn.model_selection import LeavePOut

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])

#lpo = LeavePOut(1)
#lpo = LeavePOut(2)
lpo = LeavePOut(3)    # test= 3 , other for train

lpo.get_n_splits(X)

print(lpo)
LeavePOut(p=2)

for train_index, test_index in lpo.split(X):
    print(f"TRAIN: {train_index} ,TEST: {test_index}")
    print("----------")
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f"X_train >> \n{X_train}","\n========")
    print(f"y_train >> \n{y_train}","\n========")
    print(f"X_test  >> \n{X_test}","\n========")
    print(f"y_test  >> \n{y_test}")
    print('========================================')

LeavePOut(p=3)
TRAIN: [3] ,TEST: [0 1 2]
----------
X_train >> 
[[7 8]] 
y_train >> 
[4] 
X_test  >> 
[[1 2]
 [3 4]
 [5 6]] 
y_test  >> 
[1 2 3]
TRAIN: [2] ,TEST: [0 1 3]
----------
X_train >> 
[[5 6]] 
y_train >> 
[3] 
X_test  >> 
[[1 2]
 [3 4]
 [7 8]] 
y_test  >> 
[1 2 4]
TRAIN: [1] ,TEST: [0 2 3]
----------
X_train >> 
[[3 4]] 
y_train >> 
[2] 
X_test  >> 
[[1 2]
 [5 6]
 [7 8]] 
y_test  >> 
[1 3 4]
TRAIN: [0] ,TEST: [1 2 3]
----------
X_train >> 
[[1 2]] 
y_train >> 
[1] 
X_test  >> 
[[3 4]
 [5 6]
 [7 8]] 
y_test  >> 
[2 3 4]


In [2]:
X = np.ones(10)
lpo = LeavePOut(p=3)
for train, test in lpo.split(X):
    print(f"tain: {train} > test: {test}")

tain: [3 4 5 6 7 8 9] > test: [0 1 2]
tain: [2 4 5 6 7 8 9] > test: [0 1 3]
tain: [2 3 5 6 7 8 9] > test: [0 1 4]
tain: [2 3 4 6 7 8 9] > test: [0 1 5]
tain: [2 3 4 5 7 8 9] > test: [0 1 6]
tain: [2 3 4 5 6 8 9] > test: [0 1 7]
tain: [2 3 4 5 6 7 9] > test: [0 1 8]
tain: [2 3 4 5 6 7 8] > test: [0 1 9]
tain: [1 4 5 6 7 8 9] > test: [0 2 3]
tain: [1 3 5 6 7 8 9] > test: [0 2 4]
tain: [1 3 4 6 7 8 9] > test: [0 2 5]
tain: [1 3 4 5 7 8 9] > test: [0 2 6]
tain: [1 3 4 5 6 8 9] > test: [0 2 7]
tain: [1 3 4 5 6 7 9] > test: [0 2 8]
tain: [1 3 4 5 6 7 8] > test: [0 2 9]
tain: [1 2 5 6 7 8 9] > test: [0 3 4]
tain: [1 2 4 6 7 8 9] > test: [0 3 5]
tain: [1 2 4 5 7 8 9] > test: [0 3 6]
tain: [1 2 4 5 6 8 9] > test: [0 3 7]
tain: [1 2 4 5 6 7 9] > test: [0 3 8]
tain: [1 2 4 5 6 7 8] > test: [0 3 9]
tain: [1 2 3 6 7 8 9] > test: [0 4 5]
tain: [1 2 3 5 7 8 9] > test: [0 4 6]
tain: [1 2 3 5 6 8 9] > test: [0 4 7]
tain: [1 2 3 5 6 7 9] > test: [0 4 8]
tain: [1 2 3 5 6 7 8] > test: [0 4 9]
tain: [1 2 3