In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
#----------------------------------------------------

## Splitting data:

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44, shuffle =True)    
#####################################
## logical > test_size= [0.2:0.4]  ,   
## random_state= number  >> to shuffle data when using different algorithms
#####################################

## Splitted Data:
# print(f'X_train shape : {X_train.shape}')
# print(f'X_test shape  : {X_test.shape}')
# print(f'y_train shape : {y_train.shape}')
# print(f'y_test shape  : {y_test.shape}')

In [2]:
X, y = np.arange(10).reshape((5, 2)), range(5)

print(X)
list(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[0, 1, 2, 3, 4]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

print(f"X_train >> \n{X_train}\n")
print(f"y_train >> \n{y_train}\n")
print(f"X_test  >> \n{X_test}\n")
print(f"y_test  >> \n{y_test}\n")

X_train >> 
[[8 9]
 [4 5]
 [0 1]
 [6 7]]

y_train >> 
[4, 2, 0, 3]

X_test  >> 
[[2 3]]

y_test  >> 
[1]



In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y, shuffle=True)
print(f"X_train >> \n{X_train}\n")
print(f"y_train >> \n{y_train}\n")
print(f"X_test  >> \n{X_test}\n")
print(f"y_test  >> \n{y_test}\n")

# the numbers changes when U run

X_train >> 
[[0 1]
 [8 9]
 [4 5]]

y_train >> 
[0, 4, 2]

X_test  >> 
[[6 7]
 [2 3]]

y_test  >> 
[3, 1]

