In [1]:
import numpy as np
from sklearn.model_selection import RepeatedStratifiedKFold

X=np.array([[1, 2], 
            [3, 4], 
            [5, 6], 
            [7, 8]])
y=np.array([0,
            0,
            0,
            1])

rskf = RepeatedStratifiedKFold(n_splits=2, n_repeats=2,random_state=36851234)

for train_index, test_index in rskf.split(X,y):
    print(f"TRAIN: {train_index} ,TEST: {test_index}")
    print("----------")
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f"X_train >> \n{X_train}","\n========")
    print(f"y_train >> \n{y_train}","\n========")
    print(f"X_test  >> \n{X_test}","\n========")
    print(f"y_test  >> \n{y_test}")
    print('========================================')

TRAIN: [2 3] ,TEST: [0 1]
----------
X_train >> 
[[5 6]
 [7 8]] 
y_train >> 
[0 1] 
X_test  >> 
[[1 2]
 [3 4]] 
y_test  >> 
[0 0]
TRAIN: [0 1] ,TEST: [2 3]
----------
X_train >> 
[[1 2]
 [3 4]] 
y_train >> 
[0 0] 
X_test  >> 
[[5 6]
 [7 8]] 
y_test  >> 
[0 1]
TRAIN: [1 3] ,TEST: [0 2]
----------
X_train >> 
[[3 4]
 [7 8]] 
y_train >> 
[0 1] 
X_test  >> 
[[1 2]
 [5 6]] 
y_test  >> 
[0 0]
TRAIN: [0 2] ,TEST: [1 3]
----------
X_train >> 
[[1 2]
 [5 6]] 
y_train >> 
[0 0] 
X_test  >> 
[[3 4]
 [7 8]] 
y_test  >> 
[0 1]


c:\Users\Al-arab\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
c:\Users\Al-arab\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
