In [3]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

X = np.array([1, 2, 3, 4])
y = np.array([5,6,7,8])

loo = LeaveOneOut()
loo.get_n_splits(X) 
LeaveOneOut()

LeaveOneOut()

In [4]:
for train_index, test_index in loo.split(X):            # train=(len-1) ,test=(1)
    print(f"TRAIN: {train_index} ,TEST: {test_index}")
    print("----------")
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f"X_train >> \n{X_train}","\n========")
    print(f"y_train >> \n{y_train}","\n========")
    print(f"X_test  >> \n{X_test}","\n========")
    print(f"y_test  >> \n{y_test}")
    print('========================================')

TRAIN: [1 2 3] ,TEST: [0]
----------
X_train >> 
[2 3 4] 
y_train >> 
[6 7 8] 
X_test  >> 
[1] 
y_test  >> 
[5]
TRAIN: [0 2 3] ,TEST: [1]
----------
X_train >> 
[1 3 4] 
y_train >> 
[5 7 8] 
X_test  >> 
[2] 
y_test  >> 
[6]
TRAIN: [0 1 3] ,TEST: [2]
----------
X_train >> 
[1 2 4] 
y_train >> 
[5 6 8] 
X_test  >> 
[3] 
y_test  >> 
[7]
TRAIN: [0 1 2] ,TEST: [3]
----------
X_train >> 
[1 2 3] 
y_train >> 
[5 6 7] 
X_test  >> 
[4] 
y_test  >> 
[8]


In [5]:
X = [1, 2, 3, 4]
loo = LeaveOneOut()
for train, test in loo.split(X):
    print(f"tain: {train} > test: {test}")

tain: [1 2 3] > test: [0]
tain: [0 2 3] > test: [1]
tain: [0 1 3] > test: [2]
tain: [0 1 2] > test: [3]
