In [4]:
import numpy as np
from sklearn.model_selection import RepeatedKFold

X=np.array([[1, 2],
            [3, 4], 
            [5, 6], 
            [7, 8]])
y=np.array([11, 
            22, 
            33, 
            44])

rkf = RepeatedKFold(n_splits=4, n_repeats=4, random_state=44)   # >> n_repeats <<

for train_index, test_index in rkf.split(X):
    print(f"TRAIN: {train_index} ,TEST: {test_index}")
    print("----------")
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f"X_train >> \n{X_train}","\n========")
    print(f"y_train >> \n{y_train}","\n========")
    print(f"X_test  >> \n{X_test}","\n========")
    print(f"y_test  >> \n{y_test}")
    print('========================================')

TRAIN: [0 1 2] ,TEST: [3]
----------
X_train >> 
[[1 2]
 [3 4]
 [5 6]] 
y_train >> 
[11 22 33] 
X_test  >> 
[[7 8]] 
y_test  >> 
[44]
TRAIN: [0 1 3] ,TEST: [2]
----------
X_train >> 
[[1 2]
 [3 4]
 [7 8]] 
y_train >> 
[11 22 44] 
X_test  >> 
[[5 6]] 
y_test  >> 
[33]
TRAIN: [0 2 3] ,TEST: [1]
----------
X_train >> 
[[1 2]
 [5 6]
 [7 8]] 
y_train >> 
[11 33 44] 
X_test  >> 
[[3 4]] 
y_test  >> 
[22]
TRAIN: [1 2 3] ,TEST: [0]
----------
X_train >> 
[[3 4]
 [5 6]
 [7 8]] 
y_train >> 
[22 33 44] 
X_test  >> 
[[1 2]] 
y_test  >> 
[11]
TRAIN: [0 2 3] ,TEST: [1]
----------
X_train >> 
[[1 2]
 [5 6]
 [7 8]] 
y_train >> 
[11 33 44] 
X_test  >> 
[[3 4]] 
y_test  >> 
[22]
TRAIN: [0 1 3] ,TEST: [2]
----------
X_train >> 
[[1 2]
 [3 4]
 [7 8]] 
y_train >> 
[11 22 44] 
X_test  >> 
[[5 6]] 
y_test  >> 
[33]
TRAIN: [1 2 3] ,TEST: [0]
----------
X_train >> 
[[3 4]
 [5 6]
 [7 8]] 
y_train >> 
[22 33 44] 
X_test  >> 
[[1 2]] 
y_test  >> 
[11]
TRAIN: [0 1 2] ,TEST: [3]
----------
X_train >> 
[[1 2]
 [3 4]

In [7]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 12883823

rkf = RepeatedKFold(n_splits=2, n_repeats=2, random_state=random_state)
for train, test in rkf.split(X):
    print(f"tain: {train} > test: {test}")

tain: [2 3] > test: [0 1]
tain: [0 1] > test: [2 3]
tain: [0 2] > test: [1 3]
tain: [1 3] > test: [0 2]
