In [1]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=5)
print(tscv)

for train_index, test_index in tscv.split(X):   
    print(f"TRAIN: {train_index} ,TEST: {test_index}")
    print("----------")
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(f"X_train >> \n{X_train}","\n========")
    print(f"y_train >> \n{y_train}","\n========")
    print(f"X_test  >> \n{X_test}","\n========")
    print(f"y_test  >> \n{y_test}")
    print('========================================')

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None)
TRAIN: [0] ,TEST: [1]
----------
X_train >> 
[[1 2]] 
y_train >> 
[1] 
X_test  >> 
[[3 4]] 
y_test  >> 
[2]
TRAIN: [0 1] ,TEST: [2]
----------
X_train >> 
[[1 2]
 [3 4]] 
y_train >> 
[1 2] 
X_test  >> 
[[1 2]] 
y_test  >> 
[3]
TRAIN: [0 1 2] ,TEST: [3]
----------
X_train >> 
[[1 2]
 [3 4]
 [1 2]] 
y_train >> 
[1 2 3] 
X_test  >> 
[[3 4]] 
y_test  >> 
[4]
TRAIN: [0 1 2 3] ,TEST: [4]
----------
X_train >> 
[[1 2]
 [3 4]
 [1 2]
 [3 4]] 
y_train >> 
[1 2 3 4] 
X_test  >> 
[[1 2]] 
y_test  >> 
[5]
TRAIN: [0 1 2 3 4] ,TEST: [5]
----------
X_train >> 
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]] 
y_train >> 
[1 2 3 4 5] 
X_test  >> 
[[3 4]] 
y_test  >> 
[6]
